#!/bin/sh

if [ "$old_sum" != "$new_sum" ]; then
    pnpm install
    echo -n "$new_sum" > Deploy.cache
fi

# Build the react app
pnpm run build && rm -r portfolio/ && mv build/ portfolio/ && echo "Deployed"
